In [1]:
# Import the required modules.
import pandas as pd

In [2]:
# Read the data.
df = pd.read_csv('./medquad.csv')

In [3]:
# Show the head of the df.
df.head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

In [4]:
# Show the shape of the data.
df.shape

(16412, 4)

In [5]:
# Show the counts of the data.
df.source.value_counts()

source
GHR                  5430
GARD                 5394
NIDDK                1192
NINDS                1088
MPlusHealthTopics     981
NIHSeniorHealth       769
CancerGov             729
NHLBI                 559
CDC                   270
Name: count, dtype: int64

In [6]:
# Remove unwanted spaces in the columns.
df.question = df.question.str.replace(' ?', '?')

In [7]:
# Remove unwanted spaces in the columns.
df.question = df.question.str.replace('??', '?')

In [8]:
# Remove row with duplicate questions.
df = df.drop_duplicates(subset='question')

In [9]:
# Show the shape df.
df.shape

(14984, 4)

In [10]:
# Find the list of the sources in df.
source_list = list(set(df.source))

In [11]:
# Create an empty list to store the index.
empty_list = []

In [12]:
# Create the dataframe of the selected indices.
for item in source_list:
    index_list = df[df.source==item].sample(n=20, random_state=2).index.to_list()

    for num in index_list:
        empty_list.append(num)

empty_list.sort()
df_index = df.loc[empty_list]

In [13]:
# Show the head of df_index.
df_index.head()

,question,answer,source,focus_area
3,What are the treatments for Glaucoma?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
14,What is (are) High Blood Pressure?,High blood pressure is a common disease in whi...,NIHSeniorHealth,High Blood Pressure
25,What are the treatments for High Blood Pressure?,High blood pressure is treated with lifestyle ...,NIHSeniorHealth,High Blood Pressure
63,What is (are) Osteoarthritis?,Affects Many Older People Osteoarthritis is th...,NIHSeniorHealth,Osteoarthritis
84,How to prevent Problems with Taste?,Problems with taste that occur with aging cann...,NIHSeniorHealth,Problems with Taste

In [14]:
# Check the length of df_index.
df_index.shape

(180, 4)

In [15]:
# Re-index df_index.
df_index = df_index.reset_index(drop=True)

In [16]:
# Create an id column with the index.
id_column = list(range(len(df_index)))
df_index.loc[:, 'id'] = id_column

In [17]:
# Show the head of df_index.
df_index.head()

,question,answer,source,focus_area,id
0,What are the treatments for Glaucoma?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma,0
1,What is (are) High Blood Pressure?,High blood pressure is a common disease in whi...,NIHSeniorHealth,High Blood Pressure,1
2,What are the treatments for High Blood Pressure?,High blood pressure is treated with lifestyle ...,NIHSeniorHealth,High Blood Pressure,2
3,What is (are) Osteoarthritis?,Affects Many Older People Osteoarthritis is th...,NIHSeniorHealth,Osteoarthritis,3
4,How to prevent Problems with Taste?,Problems with taste that occur with aging cann...,NIHSeniorHealth,Problems with Taste,4

In [18]:
# Rename focus_area to focus.
df_index.columns = [['question', 'answer', 'source', 'focus', 'id']]

In [19]:
# Show the head of df_index.
df_index.head()

,question,answer,source,focus,id
0,What are the treatments for Glaucoma?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma,0
1,What is (are) High Blood Pressure?,High blood pressure is a common disease in whi...,NIHSeniorHealth,High Blood Pressure,1
2,What are the treatments for High Blood Pressure?,High blood pressure is treated with lifestyle ...,NIHSeniorHealth,High Blood Pressure,2
3,What is (are) Osteoarthritis?,Affects Many Older People Osteoarthritis is th...,NIHSeniorHealth,Osteoarthritis,3
4,How to prevent Problems with Taste?,Problems with taste that occur with aging cann...,NIHSeniorHealth,Problems with Taste,4

In [20]:
# Re-arrange df.
df_index = df_index[['id', 'question', 'answer', 'focus', 'source']]

In [21]:
# Show the head of df_index.
df_index.head()

,id,question,answer,focus,source
0,0,What are the treatments for Glaucoma?,"Although open-angle glaucoma cannot be cured, ...",Glaucoma,NIHSeniorHealth
1,1,What is (are) High Blood Pressure?,High blood pressure is a common disease in whi...,High Blood Pressure,NIHSeniorHealth
2,2,What are the treatments for High Blood Pressure?,High blood pressure is treated with lifestyle ...,High Blood Pressure,NIHSeniorHealth
3,3,What is (are) Osteoarthritis?,Affects Many Older People Osteoarthritis is th...,Osteoarthritis,NIHSeniorHealth
4,4,How to prevent Problems with Taste?,Problems with taste that occur with aging cann...,Problems with Taste,NIHSeniorHealth

In [22]:
# Save df_index to disk as data.csv.
df_index.to_csv('./data.csv', index=False)